# Generated by Django 3.2.5 on 2021-08-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='language',
        ),
    ]
