# Generated by Django 3.2.5 on 2021-08-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_resume', '0002_remove_tools_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
